version: 2
jobs:
  build:
    working_directory: ~/source/py_automation
    docker:
      - image: angieslist/circleci-node:8.11.1
        auth:
           username: $DOCKER_USERNAME
           password: $DOCKER_AUTH
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start container
          command: docker-compose up -d
            
