version: 2
jobs:
  build:
    resource_class: large
    working_directory: ~/al_py_automation
    docker:
      - image: circleci/python:3.7.2
        auth:
           username: $DOCKER_USERNAME
           password: $DOCKER_AUTH
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Authenticate to DockerHub
          command: 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_AUTH"'
      - run:
          name: Build Docker image
          command: |
            docker build -t angieslist/al_py_automation:"${CIRCLE_BUILD_NUM}" -t angieslist/al_py_automation:latest .
      - run:
          name: Publish Docker image
          command: |
            docker push angieslist/al_py_automation:"${CIRCLE_BUILD_NUM}"
            docker push angieslist/al_py_automation:latest
      - run:
          name: Run docker image
          command: |
            docker run -d --name al_py_automation_al_py_automation_1 \
            -e CBT_KEY \
            -e CBT_USER \
            -e MBI_PORT \
            -e MB_HOST \
            -e PYPROXY_PORT \
            -e SAUCE_ACCESS_KEY \
            -e SAUCE_USERNAME \
            -e BASEURL_OVERRIDE=https://wwwstg.angieslist.com \
            -v `pwd`/container_reports:/al_py_automation/reports angieslist/al_py_automation:"${CIRCLE_BUILD_NUM}"
      - run: sleep 10
      - run:
          name: Run subset of tests
          command: |
            ./behave_docker_test.sh al_py_automation_al_py_automation_1 headless chrome tags circleci
            docker stop al_py_automation_al_py_automation_1
            
