version: 2
jobs:
  build:
    working_directory: ~/al_py_automation
    docker:
      - image: circleci/python:3.7.2
      # - image: angieslist/circleci-node:8.11.1
        auth:
           username: $DOCKER_USERNAME
           password: $DOCKER_AUTH
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Authenticate to DockerHub
          command: 'docker login -u "$DOCKER_USERNAME" -p "$DOCKER_AUTH"'
      - run: |
          echo 'export BASEURL_OVERRIDE=https://wwwstg.angieslist.com' >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build -t angieslist/al_py_automation:"${CIRCLE_BUILD_NUM}" -t angieslist/al_py_automation:latest .
      - run:
          name: Publish Docker image
          command: |
            docker push angieslist/al_py_automation:"${CIRCLE_BUILD_NUM}"
            docker push angieslist/al_py_automation:latest
      - run: sleep 10
      # - run:
      #     name: Running circle-tag tests
      #     command: ./behave_docker_test.sh al_py_automation_al_py_automation_1 cbt chrome tags circle
