from behave import then
from xmlrunner import xmlrunner
import unittest


@then('run visitor site unittests')
def step_impl(context):
    """This will take a VERY long time unless you comment out some lines in the list of enabled_tests below """
    appsuite_env = 'al_visitor_site'
    test_names = [appsuite_env + '.tests.' + test for test in get_visitor_site_tests()]
    tests = unittest.TestLoader().loadTestsFromNames(test_names)
    xmlrunner.XMLTestRunner(verbosity=2, output='reports').run(tests)

def get_visitor_site_tests():
    tests = unittest.TestLoader().discover('al_visitor_site/tests')
    test_list = []
    test_skiplist = get_visitor_skiplist()
    for group in tests:
        for suite in group:
            for test in suite:
                test_row = str(test)
                canonical = test_row[test_row.find("(")+1:test_row.find(")")] + '.' + test_row[:test_row.find("(")].strip()
                if not canonical in test_skiplist:
                    test_list.append(canonical)

    return test_list


def  get_visitor_skiplist():
    """
    Returns list of tests to be SKIPPED, in most cases, probably most of them
    When `behave --tags=@visitorLegacy -k` is run, any test that IS commented out or missing below will be run in succession
    """
    tests = [
            # 'test_AA404.AA404.test_aa404',
            'test_PageTemplatesTest.PageTemplatesTests.test_templates_loaded',
            # 'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesFooterJoinClick',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesHeaderBusinesscenterClick',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesHeaderFAQClick',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesHeaderITPClick',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesHeaderLinkClick',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesHeaderScClick',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesSegmentHeaderJoin',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesSegmentPagecall',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesSignInHeader',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesAtlanta',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesBoston',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesChicago',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesCincinnati',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesDallas',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesHouston',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesIndianapolis',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesLasVegas',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesLinkNYC',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesLosAngeles',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesMinneapolis',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesPittsburgh',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesSanAntonio',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesTopCitiesTampa',
            'test_PhotoGalleriesSegment.PhotoGalleriesSegmentTestCase.test_photoGalleriesfooterJoinCTA',
            'test_Redirects.RedirectsTestCase.test_redirects',
            'test_TemplateVisualChecks.TemplateVisualChecks.test_load_template_pages',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoFooterJoinClick',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoHeaderFAQClick',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoHeaderITPClick',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoHeaderLinkClick',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoHeaderScClick',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoHeaderSignInClick',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeoSegmentJoin',
            'test_companyListTreeSegment.CompanyListCatNoGeoTestCase.test_companyListCatNoGeo_topCities',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegCitySegmentPagecall',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityFooterJoinClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityHeaderBcClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityHeaderFAQClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityHeaderITPClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityHeaderLinkClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityHeaderScClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCityHeaderSignInClick',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCitySegmentJoin',
            'test_companyListTreeSegment.CompanyListRegularCityTestCase.test_companyListRegularCity_topCities',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateFooterJoinClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateHeaderBcClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateHeaderFAQClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateHeaderITPClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateHeaderLinkClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateHeaderScClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateHeaderSignInClick',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateSegmentJoin',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListStateSegmentPagecall',
            'test_companyListTreeSegment.CompanyListStatePageTestCase.test_companyListState_topCities',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListFooterJoinClick',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListHeaderFAQClick',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListHeaderITPClick',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListHeaderLinkClick',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListHeaderScClick',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListHeaderSignInClick',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListSegmentJoin',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyListSegmentPagecall',
            'test_companyListTreeSegment.CompanyListTestCase.test_companyList_topCities',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCityFooterJoinClick',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCityHeaderFAQClick',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCityHeaderITPClick',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCityHeaderLinkClick',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCityHeaderScClick',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCityHeaderSignInClick',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCitySegmentJoin',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCitySegmentPagecall',
            'test_companyListTreeSegment.CompanyListTopCityTestCase.test_companyListTopCity_topCities',
            'test_footerTopCities.FooterTopCitiesTestCase.test_footerTopCities',
            'test_h1TitleCanonical.TitleCanonicalH1TestCase.test_titleCanonicalH1',
            'test_homePageSegment.HomepageSegmentTestCase.test_homePageDrupal_Body',
            'test_homePageSegment.HomepageSegmentTestCase.test_homePageDrupal_Header',
            'test_homePageSegment.HomepageSegmentTestCase.test_homePageSegmentPagecall',
            'test_homePageSegment.HomepageSegmentTestCase.test_homePage_Footer',
            'test_homePageSegmentThunderball.HomepageTballSegmentTestCase.test_homePageTBall_Footer',
            'test_homePageSegmentThunderball.HomepageTballSegmentTestCase.test_homePageTBall_Header',
            'test_homePageSegmentThunderball.HomepageTballSegmentTestCase.test_homePageTBall_TopCity',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksFooterBusinessCenterLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksFooterFaqLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksFooterHiwLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksFooterJoinForFreeTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksFooterSolutionCenterLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksHeaderBusinessOwnerLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksHeaderFAQLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksHeaderInThePressLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksHeaderSolutionCenterLinkTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageCall',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesAtlantaTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesBostonTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesChicagoTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesCincinnatiTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesDallasTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesHoustonTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesIndianapolisTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesLasVegasTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesLosAngelesTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesMinneapolisTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesNYCTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesPittsburghTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesSanAntonioTball',
            # 'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksPageTopCitiesTampaTball',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksTBall_Header',
            'test_howItWorksThunderball.HowItWorksThunderballPageSegmentTestCase.test_howItWorksTballSignInLinkClick',
            'test_leafPage.LeafTestCase.test_leaf',
            'test_leafSegment.LeafPageSegmentTestCase.test_SignInHeaderLeafAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_SignInHeaderLeafnewAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_SignInHeaderLeafnonAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_footerJoinCTAAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_footerJoinCTANewAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_footerJoinCTAnonAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_headerJoinCTAAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_headerJoinCTAnewAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_headerJoinCTAnonAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentCTAwithZIPAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentCTAwithZIPNewAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentCTAwithoutZIP',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentCTAwithoutZIPAdvertiser',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentFooterJoinClick',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentPagecallAdvertisers',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentPagecallNewAdvertisers',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentPagecallNonAdvertisers',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesAtlanta',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesBoston',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesChicago',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesCincinnati',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesDallas',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesHouston',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesIndianapolis',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesLasVegas',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesLinkNYC',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesLosAngeles',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesMinneapolis',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesPittsburgh',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesSanAntonio',
            'test_leafSegment.LeafPageSegmentTestCase.test_leafPageSegmentTopCitiesTampa',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingHeaderAlLinkTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingHeaderBusinessOwnerLinkTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingHeaderFAQLinkTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingHeaderInThePressLinkTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingHeaderSolutionCenterLinkTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsAlbanyTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsAustinTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsCharlotteTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsDetroitTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsGreensboroTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsLPhoenixeTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsLouisvilleTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingMajorMarketsSeattleTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTballHeaderJoinClick',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTballHeaderLinkClick',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTballSegmentPagecall',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTballSignInLinkClick',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesAtlantaTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesBostonTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesChicagoTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesCincinnatiTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesDallasTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesHoustonTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesIndianapolisTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesLasVegasTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesLosAngelesTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesMinneapolisTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesNYCTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesPittsburghTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesSanAntonioTball',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMeLandscapingTopCitiesTampaTball123',
            'test_nearMeThunderball.NearMeThunderballPageSegmentTestCase.test_nearMePostalCodeLandscapingTball',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesFooterJoinClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesHIWHeaderLinkClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesHeaderFAQClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesHeaderITPClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesHeaderJoinClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesHeaderScClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesHeaderSignInClick',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_articlesSegmentPagecall',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesAtlanta',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesBoston',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesChicago',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesCincinnati',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesDallas',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesHouston',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesIndianapolis',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesLasVegas',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesLosAngeles',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesMinneapolis',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesNYC',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesPittsburgh',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesSanAntonio',
            'test_solutionCenterSegment.SolutionCenterSegmentTestCase.test_solutionCenterTopCitiesTampa',
            'test_sourceTests.CheckingSourceTestCase.test_pageSourceTest',
            'test_topCityTitle.TopCityH1TestCase.test_topCityH1',
    ]

    return tests
