# application suites should be listed by directory name and base_url
appsuites:
  al_visitor_site:
      base_url: http://visitordev3.angieslist.com
      # base_url: http://angieslist.local
      # base_url: https://wwwstg.angieslist.com
  al_visitor_tball:
      base_url: https://visitor-app-stage5.plat.angieslist.com
  al_member_site:
      base_url: https://tampa-stagegolf.plat.angieslist.com
      test_username: automation@angieslist.com
      test_password: qwerty1234!
  al_office_site:
      base_url: https://office-stage5.plat.angieslist.com
