# application suites should be listed by directory name and base_url
appsuites:
  al_visitor_site:
      base_url: https://tampa-stage4.plat.angieslist.com/app/reviews
    # base_url: https://tampa-stage4.plat.angieslist.com/app/reviews
  al_reviews:
      base_url: https://tampa-stage4.plat.angieslist.com/app/reviews