# application suites should be listed by directory name and base_url
appsuites:
  al_visitor_site:
      # base_url: http://visitordev2.angieslist.com
      base_url: http://visitordev3.angieslist.com
      # base_url: http://angieslist.local
      # base_url: https://wwwstg.angieslist.com
  al_visitor_tball:
      # base_url: https://visitor-app-stagefoxtrot.plat.angieslist.com
      # base_url: https://visitor-app-stage5.plat.angieslist.com
      base_url: https://visitor-app-stagegolf.plat.angieslist.com
  al_member_site:
      base_url: https://tampa-stage4.plat.angieslist.com
      test_username: joshua.king@homeadvisor.com
      test_password: testtest
  al_office_site:
      base_url: https://office-stage4.plat.angieslist.com
